sudo: false

language: python

python:
  - 3.6

env:
  - export APP_SETTINGS="TESTING"

install:
  - pip install -r requirements.txt

addons:
  code_climate:
    repo_token:
      secure: "d+dccm3DDJnuOfdvFCswDZUs0KLNTY0LutweQWX4XxAgjgl/br3LqnrlnrsuBrw4AKiQSxXmnr/CsGUx1vgVDpO0j5i2pDIEwHFEjrby8aNCm5B1mv+q7El+RQu5hnjCmtReheJO/bIKRm8Mb7NqZJPZ5sbsPT1KBMatkU0QAAe7NEPgOUcmVvr7/iL4r9XZtoclJODAHQTBz1l4XXTiSg3JXahHE+TbQ8znjV+Tl2L1xybgyZePDCrPrDhlGqjJMaqojKMg1xLriVldBZlUQamvYSBuSNclWwxHNG7j7VQHkyGwfsef/4ti4KlibnBFmFC3TbWvIzFF/hsMCGv7PHDcyrVsPgYH6MGrsBCygtWa9VGHL1De4H87XCCBuIw6NYuxEgEOPaEiEhD9FYJiGyqowXq05yH2JYsvm2mpvNkLnenQ3YAyfuCg+kJaC0t8osyZaaFjp8vJYVO/AHN3SC6h7vUS3G6XqWipXDIx1xFuP+zLJGOs3/KLwI+/8Ae3sej1168pvKw/xmEx14g+/iCNI3PlP9jI66a6M4xb7jFjOx5685BrXDgIFWpbF7C7eB4PFun3pzChl71+EyXB2j5IRXunTuHgFqK5TWkYAORkwYz/OsZn+rZclY1RuJatvGVaeyq/t5MEauB4+Y4zy5f6MWJNflcZiM0rkITibJY="

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - coverage run --source api --branch -m unittest discover
  - coverage report -m
  - coveralls

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  api_key:
    secure: "kHJABJd3RPT1yFAzPlY1J/c7yc1NhrvlKYZC54L+BWfcTWVYgouIXMc3SCbDRMQC+gEVbSlrLTrTvHzTtGFS5/Ut4x7x/5CEANx3sykXnVO9BuWLhVEEtBCrqFmR1G0ozxcFfw4XCKYyZoaylt7+SckiDaICf7IyMFD2JhUJ1WY0+veYkv+vpBtk/oGFGtbVOhbbp6iMayy3u6tmCC5Z2lUvv1pd2gcqqtvT5/Ow+hvjVSn7feC5R9Y58l3qxNPnnvtbBld7LgbMfBUkPn8pyXnEDNdgEwXsTsYR8cLcap6qfSdbOedslKSpykjJrshUDXqM9E3rnmvG8Nh+PcpZjlEGPKFGZS3oZp/kcbiKWPXpST4/MvwOd4GrmVGkylIqa0QGjfODM3PU7L7xn4BhoG/Wm+xAc56iqXrrIEh9SSeqs0sfCKDm9+lbdGw0RxpZhDFx3+sDpDXdlbrGcCmiEuihx+lQ4Z72HsU9UTColacO267fFg708AwGLFo5ENFwcu4J7ZJSZobXwjcpgpV2A8DZiLtJaLHKzn78765vb/RDl1mTDfzvG3d/1wYuEBRAYG41vcMXwPAFtRsB/UZlTQ1U2NYtRLVtewVXyQvCEt9pYrOsJVBFNzJIUHJxNkC03/MoJwzKbExuA7UE4vjtGnx4rUTJU2tpUDl8FDkLgLs="
  strategy: git
  app: tims-fast-food
  on: pep_improve


