sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
#  - pylint --output-format=text *.py
  - pytest
  - python -m unittest discover
  - coverage erase
  - coverage run test_api.py && coverage html


after_sucess:
  - codecov
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: IB3WzvLTka2MAk/kczOdNsBnY4wGfoD4/PpoOKbaX6rpBmKFDQRsljo7I9TaB6epo5UNoK9Bf2SIFbBtC1IdCA7BCx/DkhBBzMNOrwGLVCXkyRuuXWL+wfpTJNqV4l10wgVnWv5h+qYcqLzW9IDYHyJXBIyQKHBlWUOv5uBWZWCQEQc68HeUTCsUXuMk2LDEfpQSRHzeFZMYRbW5eN0C2EVoyrUYs1NXTbyivhYb+akKVbps7z3LLdzUdqhWz6eStXEZ4xIxCmmzGAmHmJMTNhHIrpjsFVm5jCjmDND36vDkSBhtVAgGMZiA82+Ce/88y3tVCv889HIlIjFu3WrjwUSlh8PXgsifPYHjd/6PEp1t+L3Ov6vMnAglMbw4qT2Xgplq9OzVuvkN5KFO3zuGnGkxyMT79ZeS3xK4uE0fGgFjS1ZXFg+KKQ7DD2EtcgPBFFm7J3KX+Qs5KiFpr0VMQ8kLEQV12sdxFYxwvXKZ3ZL59eOXAUaQjaEqoERQqyrq3+qb40kZpXkyW8OIit1GGo/mehRaeHpCtHk2Zq0NLGLpumFqOcP0raw6OE6Hhn1MwhjJ7X63clVSdsQXR7U1xZPwHQzGiR5BbBHu7h48RAv3z/2WlomZvP2cbWk8zTLR931YjUqKP0qOFDkb5iYlAOnoAV+eFUXnywN9spL31eM=
  strategy: git
  app: tims-fast-food
  on: api


