FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Fast Food Fast

Fast-Food-Fast is a food delivery service app for a restaurant.

## Orders [/api/v1/orders]

### List All Orders [GET]

+ Response 200 (application/json)

        {
            "orders": [
                {
                    "id": 1,
                    "item": "Chips",
                    "quantity": 1,
                    "status": "pending",
                    "user_id": 1
                },
                {
                    "id": 2,
                    "item": "Liver",
                    "quantity": 1,
                    "status": "pending",
                    "user_id": 1
                }
            ]
        }

### Create a New Order [POST]

A user may create an order using this action. It takes a JSON
object containing a user id, an item and quantity requested.

+ Request (application/json)

        { "user_id": "1", "item": "Liver", "quantity":"1" }

+ Response 201 (application/json)

    + Headers

            Content-Type: application/json

    + Body

           {
                "order": {
                    "id": 1,
                    "item": "Liver",
                    "quantity": "1",
                    "status": "pending",
                    "user_id": "1"
                }
            }